Задача 1.1: Реализовать нейрон на базе пороговой функции

In [8]:
import numpy as np

def threshold_function(x):
    return np.where(x >= 0.5, 1, 0)

# Пример использования
x_values = np.array([-1, 0, 0.5, 1, 2])
output = threshold_function(x_values)
print(output)


[0 0 1 1 1]


Задача 1.2: Реализовать нейрон на базе функции Softsign

In [9]:
def softsign(x):
    return x / (1 + np.abs(x))

# Пример использования
x_values = np.array([-2, -1, 0, 1, 2])
output = softsign(x_values)
print(output)


[-0.66666667 -0.5         0.          0.5         0.66666667]


Задача 1.3: Реализовать 3 слоя нейронов (по 2 нейрона в каждом) с использованием Softsign

In [10]:
class NeuralLayer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    def forward(self, inputs):
        return softsign(np.dot(inputs, self.weights) + self.biases)

# Создаем три слоя
layer1 = NeuralLayer(2, 2)
layer2 = NeuralLayer(2, 2)
layer3 = NeuralLayer(2, 2)

# Пример входных данных (2 входа)
input_data = np.array([[1, 2]])

# Пропускаем данные через сеть
output1 = layer1.forward(input_data)
output2 = layer2.forward(output1)
output3 = layer3.forward(output2)

print(output3)


[[-0.07583187  0.02110017]]


Задача 1.4: Определение пола с другим нормированием и альтернативной функцией активации

In [11]:
def normalize_data(data):
    mean_value = np.mean(data)
    return (data - mean_value) / mean_value

def relu(x):
    return np.maximum(0, x)

# Пример данных
data = np.array([50, 100, 150])
normalized_data = normalize_data(data)
output = relu(normalized_data)
print(output)


[0.  0.  0.5]


Задача 1.5: Решение уравнения через градиентный спуск 

In [12]:
def gradient_descent(learning_rate=0.1, epochs=1000):
    x = np.random.randn()  # Случайное начальное значение
    for i in range(epochs):
        gradient = 2 * x + 2  # Производная функции x^2 + 2x - 6
        x -= learning_rate * gradient
    return x

result = gradient_descent()
print(f"Минимальное значение функции достигается при x = {result}")


Минимальное значение функции достигается при x = -0.9999999999999998


Задача 1.6 (дополнительно): Решение уравнения через градиентный спуск

In [13]:
def gradient_descent_cubic(learning_rate=0.01, epochs=1000):
    x = np.random.randn()  # Случайное начальное значение
    for i in range(epochs):
        gradient = 3 * x**2 + 4 * x - 6  # Производная функции x^3 + 2x^2 - 6x - 1
        x -= learning_rate * gradient
    return x

result = gradient_descent_cubic()
print(f"Минимальное значение функции достигается при x = {result}")


Минимальное значение функции достигается при x = 0.8968052532744759
