[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/4vel/python-intro/blob/main/Lesson2/notebooks/9.numpy.ipynb)

# Numpy

In [7]:
import numpy as np
x = np.array([[1,0,4],[3,3,1]])
y = np.array([[2,5],[1,1],[3,2]])

In [8]:
x

array([[1, 0, 4],
       [3, 3, 1]])

In [9]:
x.dot(y)

array([[14, 13],
       [12, 20]])

In [7]:
x

array([[1, 0, 4],
       [3, 3, 1]])

In [8]:
y

array([[2, 5],
       [1, 1],
       [3, 2]])

In [10]:

x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
type(x)

numpy.ndarray

In [12]:
x.shape

(2, 3)

In [13]:
x.ndim

2

In [14]:
x.size

6

In [15]:
x.dtype

dtype('int64')

In [16]:
x.nbytes

48

In [17]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

In [18]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print(x)
print(x.nbytes)


[[1. 2. 3.]
 [4. 5. 6.]]
48


In [19]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
print(x)
print(x.nbytes)


[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
96


In [20]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.uint32)
print(x)
print(x.nbytes)

[[1 2 3]
 [4 5 6]]
24


In [21]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
print(x.nbytes, "bytes")

48 bytes


In [26]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print( x.nbytes, "bytes")

24 bytes


In [25]:

x_copy = np.array(x, dtype=float)
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:

x_copy_int = x_copy.astype(int)
x_copy_int

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

# Операции с массивами

In [28]:
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
type(my_array)

numpy.ndarray

In [29]:
my_array

array([ 2, 14,  6,  8])

In [30]:
my_array + 2

array([ 4, 16,  8, 10])

In [31]:
my_array - 1

array([ 1, 13,  5,  7])

In [32]:
my_array * 2

array([ 4, 28, 12, 16])

In [33]:
my_array / 2

array([1., 7., 3., 4.])

In [34]:
second_array = np.zeros(4) + 3
second_array

array([3., 3., 3., 3.])

In [35]:
my_array

array([ 2, 14,  6,  8])

In [36]:
my_array - second_array


array([-1., 11.,  3.,  5.])

In [37]:

second_array / my_array

array([1.5       , 0.21428571, 0.5       , 0.375     ])

In [38]:
second_array = np.ones(4) + 3
second_array

array([4., 4., 4., 4.])

In [39]:

my_array - second_array


array([-2., 10.,  2.,  4.])

In [40]:

second_array / my_array

array([2.        , 0.28571429, 0.66666667, 0.5       ])

In [41]:

second_array = np.identity(4)
second_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [43]:

second_array = np.identity(4) + 3
second_array

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

In [53]:
my_array

array([ 2, 14,  6,  8])

In [54]:
my_array - second_array

array([[-2., 11.,  3.,  5.],
       [-1., 10.,  3.,  5.],
       [-1., 11.,  2.,  5.],
       [-1., 11.,  3.,  4.]])

In [56]:
second_array / my_array

array([[2.        , 0.21428571, 0.5       , 0.375     ],
       [1.5       , 0.28571429, 0.5       , 0.375     ],
       [1.5       , 0.21428571, 0.66666667, 0.375     ],
       [1.5       , 0.21428571, 0.5       , 0.5       ]])

In [44]:

x = np.arange(3, 7, 0.5)
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [57]:
x = np.linspace(1.2, 40.5, num=100)
x

array([ 1.2       ,  1.5969697 ,  1.99393939,  2.39090909,  2.78787879,
        3.18484848,  3.58181818,  3.97878788,  4.37575758,  4.77272727,
        5.16969697,  5.56666667,  5.96363636,  6.36060606,  6.75757576,
        7.15454545,  7.55151515,  7.94848485,  8.34545455,  8.74242424,
        9.13939394,  9.53636364,  9.93333333, 10.33030303, 10.72727273,
       11.12424242, 11.52121212, 11.91818182, 12.31515152, 12.71212121,
       13.10909091, 13.50606061, 13.9030303 , 14.3       , 14.6969697 ,
       15.09393939, 15.49090909, 15.88787879, 16.28484848, 16.68181818,
       17.07878788, 17.47575758, 17.87272727, 18.26969697, 18.66666667,
       19.06363636, 19.46060606, 19.85757576, 20.25454545, 20.65151515,
       21.04848485, 21.44545455, 21.84242424, 22.23939394, 22.63636364,
       23.03333333, 23.43030303, 23.82727273, 24.22424242, 24.62121212,
       25.01818182, 25.41515152, 25.81212121, 26.20909091, 26.60606061,
       27.0030303 , 27.4       , 27.7969697 , 28.19393939, 28.59

In [62]:
np.geomspace(1, 625, num=5)



array([  1.,   5.,  25., 125., 625.])

In [64]:
np.logspace(3, 4, num=1000)

array([ 1000.        ,  1002.30754828,  1004.62042135,  1006.93863148,
        1009.26219099,  1011.59111222,  1013.92540756,  1016.26508939,
        1018.61017016,  1020.96066231,  1023.31657833,  1025.67793074,
        1028.04473209,  1030.41699495,  1032.79473192,  1035.17795563,
        1037.56667875,  1039.96091395,  1042.36067398,  1044.76597156,
        1047.17681949,  1049.59323056,  1052.01521762,  1054.44279353,
        1056.87597118,  1059.31476352,  1061.75918348,  1064.20924406,
        1066.66495828,  1069.12633917,  1071.59339982,  1074.06615333,
        1076.54461284,  1079.02879152,  1081.51870255,  1084.01435918,
        1086.51577465,  1089.02296226,  1091.53593533,  1094.05470721,
        1096.57929127,  1099.10970093,  1101.64594963,  1104.18805085,
        1106.7360181 ,  1109.2898649 ,  1111.84960482,  1114.41525147,
        1116.98681847,  1119.56431948,  1122.14776821,  1124.73717836,
        1127.33256371,  1129.93393803,  1132.54131515,  1135.15470892,
      

In [65]:
np.logspace(np.log10(3), np.log10(4), num=5)

array([3.        , 3.2237098 , 3.46410162, 3.72241944, 4.        ])

In [66]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 3, 4, 4])

In [67]:
x == y


array([ True, False, False,  True])

In [68]:

x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 4])
np.array_equal(x, y)

True

In [69]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 3, 4, 4])
x < y

array([False,  True,  True, False])

In [45]:
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)

In [46]:
x

array([False,  True, False, False])

In [47]:
y

array([ True,  True, False,  True])

In [48]:
np.logical_or(x, y)

array([ True,  True, False,  True])

In [74]:
np.logical_and(x, y)

array([False,  True, False, False])

In [76]:
x = np.array([12, 16, 57, 11])
np.logical_or(x < 13, x > 50)

array([ True, False,  True,  True])

In [77]:
x = np.array([1, 2, 3, 4])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [81]:

np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [78]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [79]:

x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [80]:

x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [67]:
x = np.arange(10,70,10).reshape(2, 3)
x

array([[10, 20, 30],
       [40, 50, 60]])

In [68]:
np.argmax(x)

5

In [51]:

x.T
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:

np.sum(x)

36

In [52]:

np.amin(x)

0

In [53]:

np.amax(x)

8

In [90]:

np.amin(x, axis=0)

array([0, 1, 2])

In [91]:

np.amin(x, axis=1)

array([0, 3, 6])

In [55]:

np.percentile(x, 90)

7.2

In [56]:

x = np.array([1, -21, 3, -3])

In [61]:

np.argmax(x)

5

In [62]:

np.argmin(x)

0

In [58]:

x = np.array([[2, 3, 5], [20, 12, 4]])
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [59]:

np.mean(x)

7.666666666666667

In [112]:

np.mean(x, axis=1)

array([ 3.33333333, 12.        ])

In [113]:

np.mean(x, axis=0)

array([11. ,  7.5,  4.5])

In [115]:
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [100]:

np.median(x)

4.5

In [101]:

np.std(x)

6.394442031083626

# Многомерные массивы

In [71]:
c = np.ones((4, 4))

In [72]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:

c * c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:

c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [76]:
y = np.arange(15).reshape(3, 5)
x = np.arange(10).reshape(2, 5)

In [109]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [110]:

new_array = np.vstack((y, x))
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [77]:

y = np.arange(15).reshape(5, 3)
x = np.arange(10).reshape(5, 2)

In [78]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [114]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [79]:

new_array = np.hstack((y, x))
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [80]:
from scipy import stats
x = np.random.rand(100, 10)

In [81]:
n, min_max, mean, var, skew, kurt = stats.describe(x)

In [82]:

new_array = np.vstack((mean, var, skew, kurt, min_max[0], min_max[1]))

In [83]:
new_array

array([[ 4.66421110e-01,  4.74294427e-01,  4.54849489e-01,
         4.96086105e-01,  5.43076046e-01,  5.58080974e-01,
         4.62854653e-01,  5.16048987e-01,  4.98603446e-01,
         5.22967895e-01],
       [ 1.05585018e-01,  8.12054663e-02,  9.37382758e-02,
         9.15021864e-02,  7.76971710e-02,  8.78365673e-02,
         8.01579458e-02,  9.01845636e-02,  8.39190022e-02,
         6.43092304e-02],
       [ 2.02628454e-01,  1.51500859e-01,  2.14527369e-01,
         6.96486495e-03, -1.71147816e-01, -3.15394713e-01,
         1.93230708e-01, -1.41313881e-01,  7.05790018e-02,
         8.34781278e-02],
       [-1.39271731e+00, -1.13732456e+00, -1.34940308e+00,
        -1.30915640e+00, -1.15159448e+00, -1.14885492e+00,
        -1.05315350e+00, -1.29844214e+00, -1.24269333e+00,
        -7.51636086e-01],
       [ 2.49274506e-03,  4.26801480e-03,  3.18649900e-04,
         6.33219547e-03,  1.10791718e-02,  1.23469034e-02,
         1.34718745e-04,  1.08875085e-02,  2.80416676e-02,
         4.

In [120]:

new_array.T


array([[ 0.48723575,  0.06958548,  0.10035182, -1.22307875,  0.01105432,
         0.98247619],
       [ 0.54447702,  0.08012244, -0.20486787, -1.0867609 ,  0.00645654,
         0.99900524],
       [ 0.48103417,  0.08543527, -0.02586215, -1.30735914,  0.01107615,
         0.95010891],
       [ 0.47471681,  0.06591027,  0.06746891, -0.91350133,  0.0203442 ,
         0.98244134],
       [ 0.48570142,  0.08060761,  0.03701235, -1.13222161,  0.00321417,
         0.99415778],
       [ 0.53180157,  0.08524676, -0.04692468, -1.23604514,  0.01725437,
         0.99017118],
       [ 0.50745501,  0.07750611,  0.04563948, -1.18087181,  0.00235816,
         0.99823898],
       [ 0.49295319,  0.08253985,  0.06433147, -1.14145096,  0.01454091,
         0.99729526],
       [ 0.4564022 ,  0.08019215,  0.38121445, -0.96584438,  0.01768677,
         0.99506729],
       [ 0.5019139 ,  0.09050178, -0.11159432, -1.38914117,  0.00608215,
         0.97649225]])

# Индексы и слайсы

In [86]:
x = ["USA", "France", "Germany", "England"]
x[2]

'Germany'

In [87]:

x = ('USA', 3, "France", 4)
x[2]

'France'

In [88]:

x = np.arange(10)

In [93]:

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:

x[5]

5

In [91]:

x[-2]

8

In [92]:

x[2:8]

array([2, 3, 4, 5, 6, 7])

In [130]:

x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:

x[2:8:2]


array([2, 4, 6])

In [94]:

x = np.reshape(np.arange(16), (4, 4))

In [95]:

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:

x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:

x[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [134]:

x[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [135]:

x = np.reshape(np.arange(16), (4, 4))

In [137]:

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [138]:

x[[0, 1, 2], [0, 1, 3]]

array([ 0,  5, 11])

In [139]:

x = np.arange(16).reshape(4, 4)

In [141]:

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [142]:

np.resize(x, (2, 2))

array([[0, 1],
       [2, 3]])

In [144]:

np.resize(x, (3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:

x = np.arange(16).reshape(4, 4)

In [146]:

y = np.arange(6).reshape(2, 3)

In [147]:

x + y

ValueError: operands could not be broadcast together with shapes (4,4) (2,3) 

In [148]:

x = np.ones(16).reshape(4, 4)

In [149]:

y = np.arange(4)

In [150]:

x * y

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [176]:

x = np.arange(4).reshape(2, 2)
x

array([[0, 1],
       [2, 3]])

In [182]:

y = np.arange(2).reshape(1, 2)
y

array([[0, 1]])

In [181]:

x * y

ValueError: operands could not be broadcast together with shapes (2,2) (1,4) 